name = "token-recovery-api"
main = "workers/worker.js"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "TOKEN_STORAGE", id = "f313ea8f0dc04c628e875029e4a74951", preview_id = "f313ea8f0dc04c628e875029e4a74951" }
]

[[durable_objects.bindings]]
name = "MonitorLock"
class_name = "MonitorLock"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MonitorLock"]

[triggers]
crons = ["*/1 * * * *"]

[vars]
CLIENT_URL = "https://tokenrecoverysystem.pages.dev"
ENABLE_INTERNAL_CRON = "false"

